name: 🚀 Deploy on push master

on: 
  push:
    branches:    
      - main 

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    
  
    
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3

    - name: Use Node js 16
    uses: actions/setup-node@v2
    with:
    node-version: '16'

   
    - name: 🔨 Build Project 
      run: |
        npm i
        npm run build
    
    - name: List output files
      run: find build/ -print

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: build/